// applications/web/src/views/oauth-authorize-page.tsx
import type { JSX } from 'react';
import type { ApplicationUser } from '@web/lib/session-authentication';

/** AUTHZ-001: one requested scope, resolved to a human-readable description, for display on the consent screen. */
export type OAuthAuthorizePageScope = {
	scope: string;
	description: string;
};

type OAuthAuthorizePageInput =
	| {
			mode: 'error';
			error: string;
	  }
	| {
			mode: 'form';
			clientName: string;
			redirectUri: string;
			transactionId: string;
			csrfToken: string;
			user: ApplicationUser;
			/** AUTHZ-001: the exact scopes this authorization will grant if approved — never more than what is shown here. */
			scopes: OAuthAuthorizePageScope[];
	  };

export function OauthAuthorizePage(input: OAuthAuthorizePageInput): JSX.Element {
	if (input.mode === 'error') {
		return (
			<main className="mx-auto mt-12 w-full max-w-2xl px-6">
				<div className="rounded-3xl border border-rose-200 bg-rose-50 p-8">
					<h1 className="text-2xl font-black text-rose-900">Authorization Error</h1>
					<p className="mt-3 text-rose-700">{input.error}</p>
					<a className="mt-6 inline-block text-sm font-semibold text-rose-700 underline" href="/">
						Back to home
					</a>
				</div>
			</main>
		);
	}

	const redirectHost = (() => {
		try {
			return new URL(input.redirectUri).host;
		} catch {
			return input.redirectUri;
		}
	})();

	return (
		<main className="mx-auto mt-12 w-full max-w-3xl px-6">
			<div className="rounded-3xl border border-slate-200 bg-white p-10 shadow-lg shadow-slate-200/40">
				<p className="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-700">
					OAuth Consent
				</p>
				<h1 className="mt-3 text-3xl font-black text-slate-900">Authorize {input.clientName}</h1>
				<p className="mt-4 text-slate-600">
					{input.clientName} is requesting access as{' '}
					<strong className="text-slate-900">{input.user.email}</strong>.
				</p>
				<p className="mt-2 text-sm text-slate-500">
					You will be redirected to <strong className="text-slate-700">{redirectHost}</strong> after
					you decide.
				</p>

				<div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-6">
					<p className="text-sm font-semibold text-slate-700">
						This will allow {input.clientName} to:
					</p>
					<ul className="mt-3 space-y-2">
						{input.scopes.map((scope) => (
							<li key={scope.scope} className="flex items-start gap-2 text-sm text-slate-600">
								<span aria-hidden="true" className="mt-0.5 text-indigo-600">
									&bull;
								</span>
								<span>{scope.description}</span>
							</li>
						))}
					</ul>
				</div>

				<div className="mt-8 flex flex-wrap items-center gap-4">
					<form method="POST" action="/oauth/authorize/approve" className="inline">
						<input type="hidden" name="transaction_id" value={input.transactionId} />
						<input type="hidden" name="csrf_token" value={input.csrfToken} />
						<button
							type="submit"
							className="rounded-xl bg-indigo-600 px-6 py-3 text-sm font-semibold text-white hover:bg-indigo-500"
						>
							Approve
						</button>
					</form>

					<form method="POST" action="/oauth/authorize/deny" className="inline">
						<input type="hidden" name="transaction_id" value={input.transactionId} />
						<input type="hidden" name="csrf_token" value={input.csrfToken} />
						<button
							type="submit"
							className="rounded-xl border border-slate-300 bg-white px-6 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-100"
						>
							Deny
						</button>
					</form>
				</div>
			</div>
		</main>
	);
}

// applications/web/src/views/oauth-authorize-page.svelte
<script lang="ts">
	import Alert from '@lostgradient/cinder/alert';
	import Button from '@lostgradient/cinder/button';
	import Card from '@lostgradient/cinder/card';
	import type { OAuthAuthorizePageInput } from '@web/views/oauth-authorize-page.types';

	let input: OAuthAuthorizePageInput = $props();

	function hostOf(redirectUri: string): string {
		try {
			return new URL(redirectUri).host;
		} catch {
			return redirectUri;
		}
	}
</script>

<main class="page">
	{#if input.mode === 'error'}
		<Alert variant="danger">
			<div class="stack-tight">
				<h1>Authorization Error</h1>
				<p>{input.error}</p>
				<p><a href="/">Back to home</a></p>
			</div>
		</Alert>
	{:else}
		<div class="stack-tight">
			<p class="eyebrow">OAuth Consent</p>
			<!--
				The page heading lives here rather than in Card's `title`: Cinder
				caps a generated card title at `h2` so a card never invents the
				document's top-level heading, and a consent screen genuinely needs
				an `h1`.
			-->
			<h1>Authorize {input.clientName}</h1>
		</div>

		<Card>
			<div class="stack">
				<div class="stack-tight">
					<p>
						{input.clientName} is requesting access as <strong>{input.user.email}</strong>.
					</p>
					<p class="muted">
						You will be redirected to <strong>{hostOf(input.redirectUri)}</strong> after you decide.
					</p>
				</div>

				<Card variant="well">
					<div class="stack-tight">
						<p><strong>This will allow {input.clientName} to:</strong></p>
						<ul>
							{#each input.scopes as scope (scope.scope)}
								<li>{scope.description}</li>
							{/each}
						</ul>
					</div>
				</Card>
			</div>

			{#snippet footer()}
				<div class="row">
					<form method="POST" action="/oauth/authorize/approve" class="inline-form">
						<input type="hidden" name="transaction_id" value={input.transactionId} />
						<input type="hidden" name="csrf_token" value={input.csrfToken} />
						<Button type="submit" variant="primary" size="lg">Approve</Button>
					</form>

					<form method="POST" action="/oauth/authorize/deny" class="inline-form">
						<input type="hidden" name="transaction_id" value={input.transactionId} />
						<input type="hidden" name="csrf_token" value={input.csrfToken} />
						<Button type="submit" variant="secondary" size="lg">Deny</Button>
					</form>
				</div>
			{/snippet}
		</Card>
	{/if}
</main>
