// applications/web/src/components/home-page.tsx
import type { JSX } from 'react';
import type { ApplicationUser } from '@web/types/user';
import { CopyButton } from '@web/components/copy-button';

export type ConnectionSummaryView = {
	clientId: string;
	clientName: string;
	earliestExpiresAt: string;
};

type HomePageProps = {
	user: ApplicationUser | null;
	baseUrl: string;
	/**
	 * SEC-005: a session-bound, one-time-per-session CSRF value for the
	 * sign-out form (`csrf-protection.ts`'s `deriveSessionCsrfToken`). Only
	 * present when `user` is, since there is no session to protect
	 * otherwise.
	 */
	signOutCsrfToken?: string;
	/**
	 * DATA-001 / S-18: the connector/consent inventory — every OAuth client
	 * currently holding at least one live access or refresh token for this
	 * user. Empty when signed out or when nothing is connected.
	 */
	connections?: ConnectionSummaryView[];
	/** Same session-bound CSRF token as `signOutCsrfToken`, reused for the revoke and revoke-all forms below. */
	connectionsCsrfToken?: string;
};

export function HomePage(props: HomePageProps): JSX.Element {
	const mcpEndpoint = `${props.baseUrl}/mcp`;

	return (
		<main className="mx-auto mt-12 w-full max-w-3xl px-6">
			<div className="rounded-3xl border border-slate-200 bg-white p-10 shadow-lg shadow-slate-200/40">
				<p className="text-xs font-semibold uppercase tracking-[0.2em] text-sky-700">Protokit</p>
				<h1 className="mt-3 text-4xl font-black tracking-tight text-slate-900">MCP OAuth Server</h1>
				<p className="mt-4 text-lg text-slate-600">
					Bun-native React server with OAuth, MCP transport, and Google sign-in.
				</p>

				{props.user ? (
					<section className="mt-8 rounded-2xl bg-slate-50 p-6">
						<p className="text-sm font-medium text-slate-500">Signed in as</p>
						<p className="mt-2 text-xl font-bold text-slate-900">{props.user.email}</p>
						<div className="mt-5 flex flex-wrap items-center gap-3">
							{/*
							 * Review round 4 / P2: a "Review OAuth Request" link to a
							 * bare `/oauth/authorize` (no `client_id`, `redirect_uri`,
							 * `response_type`, PKCE, or `resource`) always rendered
							 * that route's invalid-parameters error -- OAuth consent
							 * can only be initiated by a client carrying those
							 * parameters, never by the resource server itself. Removed
							 * rather than replaced: nothing on this page can supply a
							 * valid, configured authorization request, and the
							 * "Connected Applications" section below already covers
							 * reviewing/revoking existing grants.
							 */}
							<form method="POST" action="/auth/sign-out">
								{props.signOutCsrfToken && (
									<input type="hidden" name="csrf_token" value={props.signOutCsrfToken} />
								)}
								<button
									type="submit"
									className="inline-flex items-center rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-100"
								>
									Sign Out
								</button>
							</form>
						</div>
					</section>
				) : (
					<section className="mt-8 rounded-2xl bg-slate-50 p-6">
						<p className="text-slate-600">Sign in with Google to authorize OAuth clients.</p>
						<a
							href="/auth/google/start?callback_path=/"
							className="mt-5 inline-flex items-center rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white hover:bg-emerald-500"
						>
							Continue With Google
						</a>
					</section>
				)}

				{props.user && props.connections && props.connections.length > 0 ? (
					<section className="mt-8 rounded-2xl border border-slate-200 p-6">
						<div className="flex items-center justify-between">
							<p className="font-semibold text-slate-900">Connected Applications</p>
							<form method="POST" action="/account/connections/revoke-all">
								{props.connectionsCsrfToken && (
									<input type="hidden" name="csrf_token" value={props.connectionsCsrfToken} />
								)}
								<button
									type="submit"
									className="text-sm font-semibold text-rose-600 hover:text-rose-500"
								>
									Revoke All
								</button>
							</form>
						</div>
						<ul className="mt-4 divide-y divide-slate-200">
							{props.connections.map((connection) => (
								<li
									key={connection.clientId}
									className="flex items-center justify-between gap-4 py-3"
								>
									<span className="text-sm text-slate-700">{connection.clientName}</span>
									<form method="POST" action="/account/connections/revoke">
										{props.connectionsCsrfToken && (
											<input type="hidden" name="csrf_token" value={props.connectionsCsrfToken} />
										)}
										<input type="hidden" name="client_id" value={connection.clientId} />
										<button
											type="submit"
											className="text-sm font-medium text-slate-500 hover:text-rose-600"
										>
											Revoke
										</button>
									</form>
								</li>
							))}
						</ul>
					</section>
				) : null}

				<section className="mt-8 grid gap-4 rounded-2xl border border-slate-200 p-6 text-sm text-slate-600 md:grid-cols-2">
					<div>
						<div className="flex items-center gap-2">
							<p className="font-semibold text-slate-900">MCP Endpoint</p>
							<CopyButton text={mcpEndpoint} />
						</div>
						<code className="mt-1 block text-xs text-sky-700">{mcpEndpoint}</code>
					</div>
					<div>
						<p className="font-semibold text-slate-900">Authorization Metadata</p>
						<code className="mt-1 block text-xs text-sky-700">
							{props.baseUrl}/.well-known/oauth-authorization-server
						</code>
					</div>
				</section>
			</div>
		</main>
	);
}

// applications/web/src/components/home-page.svelte
<script lang="ts">
	import Button from '@lostgradient/cinder/button';
	import Card from '@lostgradient/cinder/card';
	import CopyButton from '@lostgradient/cinder/copy-button';
	import type { HomePageProps } from '@web/components/home-page.types';

	let {
		user,
		baseUrl,
		signOutCsrfToken,
		connections = [],
		connectionsCsrfToken,
	}: HomePageProps = $props();

	// `$derived`, not plain `const`: these read a prop, and a plain const would
	// capture only its initial value and go stale if the prop ever changed.
	const mcpEndpoint = $derived(`${baseUrl}/mcp`);
	const metadataEndpoint = $derived(`${baseUrl}/.well-known/oauth-authorization-server`);
</script>

<main class="page stack">
	<div class="stack-tight">
		<p class="eyebrow">Protokit</p>
		<h1>MCP OAuth Server</h1>
		<p class="muted">Bun-native Svelte server with OAuth, MCP transport, and Google sign-in.</p>
	</div>

	{#if user}
		<Card variant="well" title="Signed in as" headingLevel={2}>
			<div class="stack-tight">
				<p>{user.email}</p>
				<div class="row">
					<!--
						Review round 4 / P2: a "Review OAuth Request" link to a bare
						`/oauth/authorize` (no `client_id`, `redirect_uri`,
						`response_type`, PKCE, or `resource`) always rendered that
						route's invalid-parameters error -- OAuth consent can only be
						initiated by a client carrying those parameters, never by the
						resource server itself. Removed rather than replaced: nothing on
						this page can supply a valid, configured authorization request,
						and the "Connected Applications" section below already covers
						reviewing and revoking existing grants.
					-->
					<form method="POST" action="/auth/sign-out">
						{#if signOutCsrfToken}
							<input type="hidden" name="csrf_token" value={signOutCsrfToken} />
						{/if}
						<Button type="submit" variant="secondary">Sign Out</Button>
					</form>
				</div>
			</div>
		</Card>
	{:else}
		<Card variant="well">
			<div class="stack-tight">
				<p>Sign in with Google to authorize OAuth clients.</p>
				<div class="row">
					<Button href="/auth/google/start?callback_path=/" variant="primary">
						Continue With Google
					</Button>
				</div>
			</div>
		</Card>
	{/if}

	{#if user && connections.length > 0}
		<Card title="Connected Applications" headingLevel={2}>
			{#snippet footer()}
				<form method="POST" action="/account/connections/revoke-all">
					{#if connectionsCsrfToken}
						<input type="hidden" name="csrf_token" value={connectionsCsrfToken} />
					{/if}
					<Button type="submit" variant="soft-danger" size="sm">Revoke All</Button>
				</form>
			{/snippet}
			<ul class="connection-list">
				{#each connections as connection (connection.clientId)}
					<li>
						<span>{connection.clientName}</span>
						<form method="POST" action="/account/connections/revoke">
							{#if connectionsCsrfToken}
								<input type="hidden" name="csrf_token" value={connectionsCsrfToken} />
							{/if}
							<input type="hidden" name="client_id" value={connection.clientId} />
							<Button type="submit" variant="ghost-danger" size="sm">Revoke</Button>
						</form>
					</li>
				{/each}
			</ul>
		</Card>
	{/if}

	<Card title="Endpoints" headingLevel={2}>
		<div class="stack">
			<div>
				<div class="row">
					<strong>MCP Endpoint</strong>
					<CopyButton
						value={mcpEndpoint}
						label="Copy MCP endpoint"
						copiedLabel="MCP endpoint copied"
					/>
				</div>
				<code class="endpoint">{mcpEndpoint}</code>
			</div>
			<div>
				<strong>Authorization Metadata</strong>
				<code class="endpoint">{metadataEndpoint}</code>
			</div>
		</div>
	</Card>
</main>
